budget: budget.o fichiers.o releve.o
	gcc -g -o budget budget.o fichiers.o releve.o

budget.o: budget.c
	gcc -g -c budget.c

fichiers.o: fichiers.c
	gcc -g -c fichiers.c

releve.o: releve.c
	gcc -g -c releve.c